networks:
  sbnet:
    driver: bridge

services:

  spark-master:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./data:/work
    networks:
      - sbnet

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./data:/work
    networks:
      - sbnet
    depends_on:
      - spark-master
  
  jupyterlab:
    build: ./jupyterlab
    container_name: jupyterlab
    platform: linux/amd64
    ports:
      - '9999:8888'
      - '4040:4040'
    volumes:
      - ./data:/work
    environment:
      - SPARK_OPTS=--master spark://spark-master:7077
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - spark-master
    networks:
      - sbnet